sudo: false
language: node_js
node_js: 8.1
script:
- npm test
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: lQKvXB6Ej0/LJMtRR20FTkjmJHoJNZfGXwvwNohsAaphNmpjaw7F6bNcR4dOm5Yi3PwSwVQWHhrMrVa8KfGl9CRdZwSLJohOVPtGriW+e5LJQELUW6S+xFdYOxnvPp2PpmeZn+yeDEmfh6NfMr2thdACCiPkbsTgvTzeX43nUY0P1tETK8fxylSHrEn/vUz7Cab7nOHg8XpJSSmViIDLZ2FR/MT0Zi6E/Y/YSkiztvef7vXPC4XVBB1pRAOCrGQaJMouyCRUSRBSuoCeswyZoYRJSVvdxUsai/GdoFdivmykB4cBsOcpG/GZa0aK/eKCk14YxhKy0JkEqDukWhMKF5LYAM9BHawr1OAJe0Kz6UtrUrCce5UxzwLRgg5mdCEILk1638o6/kf7iU37P17/vFqH7Nru+Z46eLzUCis0/+6cZHyLG/+pA+qqNDGc7cfFqw+mqNePiWcy9yFo8kSvWAsoe4wFkDK/r1doZ9PEs1P4FoKLe1Rumkpe6duOGk8t19Nwj8IorLuZU/GEBZwaGr75zH6eeaISzXqrrgbxXKXlpqCWDjr9Xtq3Gsb/ZqBouaTvy9gvrngTI6TEzT1DAw1xWTY5CEy8qnievjdQdycPF9EdUaMsklbJUR6g+ccvvLT/MCg8NfwHEaCfcze8jdtMfrVVid6azErj6rTQSFs=
  email:
    secure: nnvYganHIpwyi2iPs92uvN/96/gcCzAgIYSMZ487khnK2A9BjPYzeqCZPrqZjskNbwCNveqr7HwGq9nJqT6CI7e64rY/o5jptwmj+bvHM9RojLj84WGMGGuXfnbSeDDqbaSaSyd8HNygfYDqWRD5c5qwGSYc0lEWkij591+aIlgBlJIqEUeKi5/hEuzoR/9YjoYXVbbPAgdxU62OTl/DWgmmWrbzYY4JaNPY8cJUGZKUiemMUItqIlXSJRPPHtLuIyTxJTnidP53YFq3yYi8CznA+MWc+9yOD+y3EBThW0M8Na7z70PsE9/5lnyBgaNVRWiwvM8rLoyOVRnaPj45RrWCKR65B3NJqR/oBPZNiww2JMwrlSgXpucw8dbT3fO3gtNEJULW26n6qrb4YfuFWCSYzCWoMgMYW52A3+QJ68kVZRIFC+Rb9pb1vLtMOxOyndmItIfpgdtbEGYpAElOMRTogtZgvYvqgA+hM+fqaZBM8gpFK0GAEUbFcrb8y0DDg1p6C+z9b0U9xcA+LKc6FUcL1FmcrxprBmcrLHjcwQqmIRlvBL3Bc2oZSL4JE6rutp8WyAfcLEiIxNqlOIxTDvJYpjWEIo6smYTtdyHULepjQLPfbnPgA6Cdcn/j/JtRsBaeovert87jztS+w8+pwr5c3IgbRr9XEVW+SZnmF5Y=
